### ISSUE TITLE
Think about implement a global state

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#29]
Need to think about it. Is it mandatory ?

**Comment by analuspi** [comment]
I would like to do this one with you.

**Comment by julbrs** [comment]
for sure or let's get a look on the [Context](https://www.taniarascia.com/using-context-api-in-react/) API, seems useful if we don't want to implement a full Redux global state.

**Comment by analuspi** [comment]
We can schedule a meeting to talk about it?

**Comment by analuspi** [comment]
I implemented the Context Api to render the "Créer" NavLink only if we are logged In.
I also put some comments in the code to explain that.
But I don't know if it's working, because I'm not able to log in haha :cry: 
Maybe we could check this together? (I've just found out that my BootCamp classes will be at night, so I will have some time during the day)

**Comment by analuspi** [comment]
So it's working :smile:  
When we google login the "Créer" NavLink appears (the option isn't visible without login). Now I just need to figure out how to come back to the original state when we logout!

**Comment by julbrs** [comment]
FYI I have just merged `develop` in the branch `feature/context-api` 😄 only a single conflict, easy fix !!
